config/routes.rb
Rails.application.routes.draw do

  get '/calculate', to: 'bookings#calculate'
  get '/timeline_data', to: 'admin/bookings#timeline_data'

  get '/timeline_groups', to: 'admin/bookings#timeline_groups'
  get '/timeline_items', to: 'admin/bookings#timeline_items'

  scope '/:locale' do
    post 'bookings/room', to: 'bookings#room', as: 'room_booking'
    get 'bookings/success', to: 'bookings#success', as: 'success_booking'

    get 'hh/:key', to: 'pages#show', as: 'page'

    resources :bookings
    resources :room_bookings
    resources :rooms
    devise_for :users
    resources :users

    get 'kontakty', to: 'static_pages#contacts', as: 'contacts'
    get 'spa', to: 'static_pages#spa', as: 'spa'
    get 'restaurace', to: 'static_pages#restaurant', as: 'restaurant'
    get 'pokoj', to: 'static_pages#rooms', as: 'pokoje'

    root to: 'static_pages#homepage'

    namespace :admin do
      resources :pages
      resources :pictures
      resources :bookings
      resources :rooms
      resources :users

      get 'timeline', to: 'bookings#timeline', as: 'timeline'
    end

  end

  get '/', to: 'static_pages#homepage'

end

app/views/admin/pages/_form.html.slim
= simple_form_for [:admin, @page], html: {multipart: true} do |f|
  = f.error_notification

  .row
    .col-sm-6
      .form-input
        = f.input :title
      = f.input :perex
    .col-sm-6
      = f.input :language, :as => :select, :collection => Page.languages.keys.to_a, disabled: true
      = f.input :web, :as => :select, :collection => Page.webs.keys.to_a, disabled: true

  .row
    .col-sm-12
      = f.cktext_area :content

  .row
    .col-sm-6
      = f.input :key, disabled: true
  
  hr
  .row
    .col-sm-12
      - @page.pictures.each do |photo|
        .photo-wrapper
          = image_tag photo.image.url(:thumb), class: 'img-thumbnail'
          = link_to [:admin, photo], :method => :delete,
                                     :confirm => 'Are you sure?',
                                     :class => 'remove'
            = fa_icon 'remove'

    hr
    .col-sm-12
      = file_field_tag "images[]", type: :file, multiple: true

  hr
  .form-actions
    = f.button :submit, class: 'btn btn-success'

app/views/admin/pages/edit.html.slim
.container
  h1 Úprava stránky

  == render 'form'

  br
  = link_to 'zpět', admin_pages_path, class: 'btn btn-default btn-sm'

app/views/admin/pages/index.html.slim
.container
  .row
    .col-sm-3
      = render 'admin/shared/menu'
    .col-sm-9
      h1 Obsahové stránky

      table.table.table-condensed
        thead
          tr
            th Název stránky
            th Jazyková mutace
            th Typ webu
            th Poslední úprava
            th
        tbody
          - @pages.each do |page|
            tr
              td: b = page.title
              td = page.language
              td = page.web
              td = page.updated_at
              td
                .btn-group.pull-right
                  = link_to 'upravit', edit_admin_page_path(page.id), class: 'btn btn-info btn-sm'