config/routes.rb
Rails.application.routes.draw do

  get '/calculate', to: 'bookings#calculate'
  get '/timeline_data', to: 'admin/bookings#timeline_data'

  get '/timeline_groups', to: 'admin/bookings#timeline_groups'
  get '/timeline_items', to: 'admin/bookings#timeline_items'

  scope '/:locale' do
    post 'bookings/room', to: 'bookings#room', as: 'room_booking'
    get 'bookings/success', to: 'bookings#success', as: 'success_booking'

    get 'hh/:key', to: 'pages#show', as: 'page'

    resources :bookings
    resources :room_bookings
    resources :rooms
    devise_for :users
    resources :users

    get 'kontakty', to: 'static_pages#contacts', as: 'contacts'
    get 'spa', to: 'static_pages#spa', as: 'spa'
    get 'restaurace', to: 'static_pages#restaurant', as: 'restaurant'
    get 'pokoj', to: 'static_pages#rooms', as: 'pokoje'

    root to: 'static_pages#homepage'

    namespace :admin do
      resources :pages
      resources :pictures
      resources :bookings
      resources :rooms
      resources :users

      get 'timeline', to: 'bookings#timeline', as: 'timeline'
    end

  end

  get '/', to: 'static_pages#homepage'

end

app/models/room.rb
class Room < ActiveRecord::Base
  enum room_type: [:room, :service]
  after_initialize :set_default_type, :if => :new_record?

  has_many :room_bookings

  def set_default_type
    self.room_type ||= :room
  end

end

app/controllers/admin/rooms_controller.rb
class Admin::RoomsController < ApplicationController
  before_filter lambda { @body_class = 'admin' }
  before_action :set_room, only: [:show, :edit, :update, :destroy]

  # GET /rooms
  # GET /rooms.json
  def index
    @rooms = Room.all
  end

  # GET /rooms/1
  # GET /rooms/1.json
  def show
  end

  # GET /rooms/new
  def new
    @room = Room.new
  end

  # GET /rooms/1/edit
  def edit
  end

  # POST /rooms
  # POST /rooms.json
  def create
    @room = Room.new(room_params)

    respond_to do |format|
      if @room.save
        format.html { redirect_to @room, notice: 'Room was successfully created.' }
        format.json { render :show, status: :created, location: @room }
      else
        format.html { render :new }
        format.json { render json: @room.errors, status: :unprocessable_entity }
      end
    end
  end

  # PATCH/PUT /rooms/1
  # PATCH/PUT /rooms/1.json
  def update
    respond_to do |format|
      if @room.update(room_params)
        format.html { redirect_to @room, notice: 'Room was successfully updated.' }
        format.json { render :show, status: :ok, location: @room }
      else
        format.html { render :edit }
        format.json { render json: @room.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /rooms/1
  # DELETE /rooms/1.json
  def destroy
    @room.destroy
    respond_to do |format|
      format.html { redirect_to rooms_url, notice: 'Room was successfully destroyed.' }
      format.json { head :no_content }
    end
  end

  private
    # Use callbacks to share common setup or constraints between actions.
    def set_room
      @room = Room.find(params[:id])
    end

    # Never trust parameters from the scary internet, only allow the white list through.
    def room_params
      params.require(:room).permit(:name, :description, :room_type, :price_night, :price_first_hour, :price_next_hour)
    end
end

app/controllers/rooms_controller.rb
class RoomsController < ApplicationController
  before_action :set_room, only: [:show, :edit, :update, :destroy]

  # GET /rooms
  # GET /rooms.json
  def index
    @rooms = Room.all
  end

  # GET /rooms/1
  # GET /rooms/1.json
  def show
  end

  # GET /rooms/new
  def new
    @room = Room.new
  end

  # GET /rooms/1/edit
  def edit
  end

  # POST /rooms
  # POST /rooms.json
  def create
    @room = Room.new(room_params)

    respond_to do |format|
      if @room.save
        format.html { redirect_to @room, notice: 'Room was successfully created.' }
        format.json { render :show, status: :created, location: @room }
      else
        format.html { render :new }
        format.json { render json: @room.errors, status: :unprocessable_entity }
      end
    end
  end

  # PATCH/PUT /rooms/1
  # PATCH/PUT /rooms/1.json
  def update
    respond_to do |format|
      if @room.update(room_params)
        format.html { redirect_to @room, notice: 'Room was successfully updated.' }
        format.json { render :show, status: :ok, location: @room }
      else
        format.html { render :edit }
        format.json { render json: @room.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /rooms/1
  # DELETE /rooms/1.json
  def destroy
    @room.destroy
    respond_to do |format|
      format.html { redirect_to rooms_url, notice: 'Room was successfully destroyed.' }
      format.json { head :no_content }
    end
  end

  private
    # Use callbacks to share common setup or constraints between actions.
    def set_room
      @room = Room.find(params[:id])
    end

    # Never trust parameters from the scary internet, only allow the white list through.
    def room_params
      params.require(:room).permit(:name, :description)
    end
end

app/helpers/admin/rooms_helper.rb
module Admin::RoomsHelper
end

app/helpers/rooms_helper.rb
module RoomsHelper
end

app/views/admin/rooms/_form.html.slim
= simple_form_for [:admin, @room], html: {multipart: true} do |f|
  = f.error_notification
  
  .row
    .col-sm-6
      .form-input
        = f.input :name
      .form-input
        = f.select :room_type, options_for_select([:room, :service])

  hr
  .row
    .col-sm-6
      .form-input
        = f.input :price_night
      .form-input
        = f.input :price_first_hour
      .form-input
        = f.input :price_next_hour

  hr
  .form-actions
    = f.button :submit, class: 'btn btn-success'

app/views/admin/rooms/edit.html.slim
.container
  h1 Úprava pokoje

  == render 'form'

  br
  = link_to 'zpět', admin_pages_path, class: 'btn btn-default btn-sm'

app/views/admin/rooms/index.html.slim
.container
  .row
    .col-sm-3
      = render 'admin/shared/menu'
    .col-sm-9
      h1 Pokoje
      = link_to 'nový pokoj', new_admin_room_path, class: 'btn btn-sm btn-primary pull-right'

      table.table.table-condensed
        thead
          tr
            th Id
            th Název
            th Typ
            th Noc
            th První hodina
            th Další hodina
            th
        tbody
          - @rooms.each do |room|
            tr
              td: b = room.id
              td = room.name
              td = room.room_type
              td = room.price_night
              td = room.price_first_hour
              td = room.price_next_hour
              td
                .btn-group.pull-right
                  = link_to 'upravit', edit_admin_room_path(room.id), class: 'btn btn-info btn-sm'

app/views/admin/rooms/new.html.slim
.container
  h1 New room

  == render 'form'

  = link_to 'Back', rooms_path