config/routes.rb
Rails.application.routes.draw do

  get '/calculate', to: 'bookings#calculate'
  get '/timeline_data', to: 'admin/bookings#timeline_data'

  get '/timeline_groups', to: 'admin/bookings#timeline_groups'
  get '/timeline_items', to: 'admin/bookings#timeline_items'

  scope '/:locale' do
    post 'bookings/room', to: 'bookings#room', as: 'room_booking'
    get 'bookings/success', to: 'bookings#success', as: 'success_booking'

    get 'hh/:key', to: 'pages#show', as: 'page'

    resources :bookings
    resources :room_bookings
    resources :rooms
    devise_for :users
    resources :users

    get 'kontakty', to: 'static_pages#contacts', as: 'contacts'
    get 'spa', to: 'static_pages#spa', as: 'spa'
    get 'restaurace', to: 'static_pages#restaurant', as: 'restaurant'
    get 'pokoj', to: 'static_pages#rooms', as: 'pokoje'

    root to: 'static_pages#homepage'

    namespace :admin do
      resources :pages
      resources :pictures
      resources :bookings
      resources :rooms
      resources :users

      get 'timeline', to: 'bookings#timeline', as: 'timeline'
    end

  end

  get '/', to: 'static_pages#homepage'

end

app/models/room_booking.rb
class RoomBooking < ActiveRecord::Base
  belongs_to :room
  belongs_to :booking
end

app/controllers/room_bookings_controller.rb
class RoomBookingsController < ApplicationController
  before_action :set_room_booking, only: [:show, :edit, :update, :destroy]

  # GET /room_bookings
  # GET /room_bookings.json
  def index
    @room_bookings = RoomBooking.all
  end

  # GET /room_bookings/1
  # GET /room_bookings/1.json
  def show
  end

  # GET /room_bookings/new
  def new
    @room_booking = RoomBooking.new
  end

  # GET /room_bookings/1/edit
  def edit
  end

  # POST /room_bookings
  # POST /room_bookings.json
  def create
    @room_booking = RoomBooking.new(room_booking_params)

    respond_to do |format|
      if @room_booking.save
        format.html { redirect_to @room_booking, notice: 'Room booking was successfully created.' }
        format.json { render :show, status: :created, location: @room_booking }
      else
        format.html { render :new }
        format.json { render json: @room_booking.errors, status: :unprocessable_entity }
      end
    end
  end

  # PATCH/PUT /room_bookings/1
  # PATCH/PUT /room_bookings/1.json
  def update
    respond_to do |format|
      if @room_booking.update(room_booking_params)
        format.html { redirect_to @room_booking, notice: 'Room booking was successfully updated.' }
        format.json { render :show, status: :ok, location: @room_booking }
      else
        format.html { render :edit }
        format.json { render json: @room_booking.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /room_bookings/1
  # DELETE /room_bookings/1.json
  def destroy
    @room_booking.destroy
    respond_to do |format|
      format.html { redirect_to room_bookings_url, notice: 'Room booking was successfully destroyed.' }
      format.json { head :no_content }
    end
  end

  private
    # Use callbacks to share common setup or constraints between actions.
    def set_room_booking
      @room_booking = RoomBooking.find(params[:id])
    end

    # Never trust parameters from the scary internet, only allow the white list through.
    def room_booking_params
      params.require(:room_booking).permit(:room_id, :booking_id, :book_from, :book_to)
    end
end

app/helpers/room_bookings_helper.rb
module RoomBookingsHelper
end

app/views/room_bookings/_form.html.slim
= simple_form_for(@room_booking) do |f|
  = f.error_notification

  .form-inputs
    = f.input :room_id
    = f.input :booking_id
    = f.input :book_from
    = f.input :book_to

  .form-actions
    = f.button :submit

app/views/room_bookings/edit.html.slim
h1 Editing room_booking

== render 'form'

= link_to 'Show', @room_booking
'|
= link_to 'Back', room_bookings_path

app/views/room_bookings/index.html.slim
h1 Listing room_bookings

table
  thead
    tr
      th Room
      th Booking
      th Book from
      th Book to
      th
      th
      th

  tbody
    - @room_bookings.each do |room_booking|
      tr
        td = room_booking.room_id
        td = room_booking.booking_id
        td = room_booking.book_from
        td = room_booking.book_to
        td = link_to 'Show', room_booking
        td = link_to 'Edit', edit_room_booking_path(room_booking)
        td = link_to 'Destroy', room_booking, data: {:confirm => 'Are you sure?'}, :method => :delete

br

= link_to 'New Room booking', new_room_booking_path

app/views/room_bookings/new.html.slim
h1 New room_booking

== render 'form'

= link_to 'Back', room_bookings_path

app/views/room_bookings/show.html.slim
p#notice = notice

p
  strong Room:
  = @room_booking.room.name
p
  strong User:
  = @room_booking.booking.user.name
p
  strong Booking:
  = @room_booking.booking_id
p
  strong Book from:
  = @room_booking.book_from
p
  strong Book to:
  = @room_booking.book_to

= link_to 'Edit', edit_room_booking_path(@room_booking)
'|
= link_to 'Back', room_bookings_path